# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc26d130a7dbed1a063ff0a19340eef099e17aea4ad30403aaf092e6086ecf3db7b0cb4d599b788391c9f30d8ab4036084d8cd2b9b8b8c75f0d898c005505a7

test:
  secret_key_base: 2d016b3642ed273826b1cad2cfd5903dc92f966c4644c20761d9c510010e52f1b0226cb5e3d156356f9725d0cf1fc65aeee8295ecf11e56ff222c53e15845e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
